version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: ${MONGO_URI}
    networks:
      - GreenSage

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: m7moudshayeb
      MONGO_INITDB_ROOT_PASSWORD: m7moudshayeb
      MONGO_INITDB_DATABASE: Sari
    networks:
      - GreenSage
    volumes:
      - mongo-data:/data/db

networks:
  GreenSage:
    driver: bridge

volumes:
  mongo-data: {}
